import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import { Header } from "../components/header/Header";

const roboto = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans bg-neutral-900`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
